# Generated by Django 2.2.9 on 2020-01-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='High Street', max_length=100)),
                ('number', models.DecimalField(decimal_places=0, default='120', max_digits=5)),
                ('postcode', models.CharField(default='HP1 3AR', max_length=12)),
                ('town', models.CharField(default='Hemel Hempstead', max_length=100)),
                ('email', models.EmailField(default='info@callingmrschristmas.com', max_length=254)),
            ],
        ),
    ]
