# Generated by Django 2.2.9 on 2020-01-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=2000)),
                ('date_sent', models.DateField(auto_now=True)),
                ('reply', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_replied', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
