# Generated by Django 2.2.7 on 2019-12-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20191204_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
