# Generated by Django 2.2.9 on 2020-01-25 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='date_sent',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
