# Generated by Django 2.2.8 on 2019-12-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('name_for_image', models.CharField(max_length=100)),
                ('img_alt', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='service',
            old_name='image_description',
            new_name='img_alt',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='img_name',
            field=models.CharField(default='service-image', max_length=100),
            preserve_default=False,
        ),
    ]
