# Generated by Django 2.2.8 on 2019-12-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20191213_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategory',
            old_name='name_for_image',
            new_name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='tagline',
            field=models.CharField(default="Catching people's attention", max_length=100),
            preserve_default=False,
        ),
    ]
