# Generated by Django 2.2.8 on 2019-12-14 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20191214_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ServiceCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceCategory'),
            preserve_default=False,
        ),
    ]
