# Generated by Django 2.2.8 on 2019-12-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_servicecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='ServiceCategory',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default='wrapping', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.ServiceCategory', to_field='name'),
            preserve_default=False,
        ),
    ]
