# Generated by Django 2.2.8 on 2019-12-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20191214_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='price_in_p',
            field=models.IntegerField(default=499),
            preserve_default=False,
        ),
    ]
