# Generated by Django 2.2.9 on 2020-01-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20200130_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='street_address2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
