# Generated by Django 2.2.8 on 2019-12-07 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_employee_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('client_first_name', models.CharField(max_length=100)),
                ('client_last_name_initial', models.CharField(max_length=1)),
                ('client_company', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('casestudy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.CaseStudy')),
            ],
        ),
    ]
