# Generated by Django 2.2.8 on 2019-12-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_casestudy_casestudyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='client_last_name_initial',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
