# Generated by Django 2.2.8 on 2019-12-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20191207_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudyimage',
            name='alt',
            field=models.CharField(default="Carter's Photos", max_length=100),
            preserve_default=False,
        ),
    ]
